### ISSUE TITLE
Build docker image with tagged version

### ISSUE THREAD

**Issue by onedr0p** [jesec/rtorrent#12]
Currently there's only `:latest` any chance you can update the workflow to also tag it with the tag name, e.g. `:v0.9.8-r8` ?

Thanks!

**Comment by jesec** [comment]
https://github.com/jesec/rtorrent/discussions/3#discussioncomment-294644

Though, I think I can probably do that next week.

**Comment by jesec** [comment]
`0.9.8-r9` is now available.

**Comment by jesec** [comment]
Feel free to close the issue.
