### ISSUE TITLE
Broken autodl-irssi on v0.9.8-r12

### ISSUE THREAD

**Issue by KyleSanderson** [jesec/rtorrent#18]
Hi Jesec,

Thank you very much for taking this work on and continuing the work that @rakshasa was doing. I'm using the latest release and autodl-irssi fails to communicate properly with rtorrent. I noticed https://github.com/jesec/rtorrent/commit/fff94b312f22672d5e5321dabf2ced2efabb4496 which didn't set the content type previously.

Could you please spin a new release when you have a moment and I can help test(?). My container is using Ubuntu (so the deb package would be appreciated).

**Comment by jesec** [comment]
I will tag it soon. Meanwhile, please try the rolling build, and let me know if the issue has been resolved.

**Comment by KyleSanderson** [comment]
Still broken with xml on -r13.

**Comment by jesec** [comment]
I am not able to reproduce.

**Comment by KyleSanderson** [comment]
ACK. -r12 indeed doesn't work, but -r13 appears to work now. The issue (I think) was starting flood, which would kick rtorrent into json mode, then was unable to process any following xmlrpc requests. Anyway, as it seems to work for me now I'm going to close the issue. Thanks for the new tagged code (and for whatever you did to try it). I'll re-open if it isn't fixed, but for now it's looking good.
