### ISSUE TITLE
Unable to override `method.insert` configurations

### ISSUE THREAD

**Issue by m3Lith** [jesec/rtorrent#22]
I want to use a custom `.rtorrent.rc` config, extending the default config, as per https://github.com/jesec/rtorrent/blob/master/doc/rtorrent.rc instructions.

The problem: all the command definitions using `method.insert` can't be redefined, e.g., if I would add a line for `method.insert = cfg.download` with a different assignment in my custom config, rtorrent would throw "Invalid key" error and fail to start. In order to have my custom value, I need to use a different name (e.g., `method.insert = cfg.download2`). And then don't forget to override the usage as well, in this case `directory.default.set` option.

I'm not sure if this can be "fixed" in a straightforward way, or maybe that's just the way `method.insert` assignments work. Especially considering you explicitly create directories in the default config as well.

**Comment by jesec** [comment]
The default directory structure is not supposed to be altered if you wish to extend the config. 

You can still use `directory.default.set` command, though. The `cfg.*` entries are not used elsewhere.
