### ISSUE TITLE
Explain link to Rakshasa's repo in the readme

### ISSUE THREAD

**Issue by charsi** [jesec/rtorrent#29]
Hello 

It'll be great if you could add a blurb about the status of this project in relation to Rakshasa's. 
I was wondering why this wasn't marked as a fork but looking at #27 gave me the info I needed. It'll be nice if this info was right there in the README.md

Thanks for the free software :+1:

**Comment by jesec** [comment]
I think the README is quite clear. 

GitHub "fork" is almost always a bad idea, especially when the changes are not going to land in the parent repo. It is only useful when you want to open pull requests to the parent repo, or if you don't know how to type `git` commands, or if you are too lazy to type them.

Many features, including but not limited to Code Search, are not available to a "forked" repo. For GitHub, the forked repo is not an independent repo. It is merely a branch of parent repo. Additionally, the only official way to convert from "Fork" to normal repo is to delete the repo, and recreate one with the same name. (of course, GitHub staffs may be able to do that while preserving the contents, but there is no button).

**Comment by charsi** [comment]
I understand why making this a fork is not a good idea. The issue I linked to above made that clear.

From the readme at least I couldn't figure out easily how this was related to the original. 

With context I can kind of make sense now from the line starting with "This distribution focuses ..". But I think there should at the very least be a link to the original repo in the readme.

**Comment by jesec** [comment]
There is a link, though....

**Comment by charsi** [comment]
dammit. I see it now.
