### ISSUE TITLE
Multi user support

### ISSUE THREAD

**Issue by albertofustinoni** [jesec/rtorrent#33]
Would it be possible to add multi user support to rtorrent? By that I mean being able to run one instance of rtorrent but presenting independent lists of running torrents (and allowing each user to add/remove torrents independently) according to a user parameter passed in RPC calls. Basically make RPC calls behave like any standard multi-user web API.

Intended use case would be running rtorrent as a daemon in the context of its own user with a webUI like flood or transmission as the front-end, and having the web server relay the ID of the logged in user to RPC calls.

**Comment by Germwalker** [comment]
You can start multiple sessions of rTorrent via the startup script, juste change the service name, working directory and user/group. Than you make the same thing with multiples flood instances, one by rtorrent service. You'll need to modify the **scgi_port = 127.0.0.1:4865** inside **.rtorrent.rc** to match flood/rtorrent. Then you can reverse proxy to floods ports with a web server like nginx.

You'll have _https://user1.myseedbox.com_, _https://user2.myseedbox.com_ ...

**Comment by jesec** [comment]
^ simply run multiple instances of rTorrent.
