### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by Germwalker** [jesec/rtorrent#34]
Hello, 

I went from rtorrent 0.9.6 from rakshasa to your fork because i was less buggy and it got the console less launch mode. 
However, when i had a few To/month with the 0.9.6, now all torrents are on error state and i see rtorrent freezeing for few seconds. _jesec/rtorrent 0.9.8_ is always using **100%** of the CPU while _rakshasa/rtorrent 0.9.6_ was peaking at ~50% with the same .rtorrent.rc and and session, i just updated bins.

I have ~600 torrents.

Some of the torrents error messages : 
- Tracker: [Timed out]
- Tracker: [Couldn't connect to server]

This is the CPU usage trace that let me think rtorrent process is stalling : 
![100](https://user-images.githubusercontent.com/56682696/161387821-f641e490-2055-4601-8186-5f0eea0c82bf.PNG)

Flood is also sometimes stalling on the rtorrent interface, that didn't happend with _rakshasa/rtorrent 0.9.6_.

I know this version has some issues with the UDP DNS resolution that make rtorrent stall, so i have a local dnsmask server as DNS caching. My first resolv.conf line is _nameserver 127.0.0.1_. 

How to make it work like it should ? 

[EDIT] : stopping all torrents solve the problem. I guess it's the UDP nameserver resolution error. How can i track the bad UDP torrents or stop only UDP torrents ?

**Comment by jesec** [comment]
Disable UDP. UDP tracker is rarely used.

rTorrent can not do asynchronous DNS resolve for UDP tracker at this moment. 

It is a current technical priority to implement that.
