### ISSUE TITLE
sonarr connection to rtorrent directly

### ISSUE THREAD

**Issue by renlord** [jesec/rtorrent#4]
any ideas how to setup sonarr to connect to this container instance directly?

is it necessary to setup a scgi proxy to connect to his container instance.

I expose the scgi interface using `network.scgi.open_port=0.0.0.0:5000` and keep them in an isolated docker network.

**Comment by jesec** [comment]
It is extremely dangerous to expose rTorrent’s XMLRPC interface via a port. Be aware that by default, Docker’s `-p` exposes the port to 0.0.0.0. See security section of Flood’s wiki for more details.

Sonarr can interact with secure and controlled API interfaces of Flood natively. (see Sonarr/Sonarr#4159)

if you understand the risks and still wish to continue, there are two approaches:

1. Set a HOME env variable that points to your own mounted folder with a `.rtorrent.rc` in it. Alternatively, mount your own `.rtorrent.rc` to `/home/download/.rtorrent.rc`. It is recommended to expand upon the default configuration via `import = /etc/rtorrent/rtorrent.rc`. 
2. Simply use command arguments. `-o network.scgi.open_port=0.0.0.0:5000`

**Comment by renlord** [comment]
the unix domain socket approach is unworkable when used in docker swarm mode especially when the volume mount is over NFS unless both containers are constrained to operating on the same host and their shared volume sits on the same host.

As i understand when running the containers in an overlay network, these containers cant be accessed remotely from outside the network.
