### ISSUE TITLE
404 for rtorrent docker configuration

### ISSUE THREAD

**Issue by connected201** [jesec/rtorrent#5]
Hi, i received 404 for 
![image](https://user-images.githubusercontent.com/20506433/107035510-f4994800-67c0-11eb-8655-19ae3c3d7844.png)
URL: [https://github.com/jesec/flood/blob/master/Dockerfile.rtorrent](url)
best regards

**Comment by jesec** [comment]
Dockerfiles are moved to https://github.com/jesec/flood/tree/master/distribution/containers.

Documentations will be updated later.
