### ISSUE TITLE
Can't run any commands like bash, mkdir, ls in container

### ISSUE THREAD

**Issue by peioe** [jesec/rtorrent#68]
I am trying to switch from wonderfall's rtorrent-flood to this image + flood, and I don't know if this is expected, but I think this is what is preventing me from moving completed downloads:

> 
> docker exec -it rtorrent-peioe "mkdir --help"
> OCI runtime exec failed: exec failed: unable to start container process: exec: "mkdir --help": executable file not found in $PATH: unknown

> docker exec -it rtorrent-peioe ls
> OCI runtime exec failed: exec failed: unable to start container process: exec: "ls": executable file not found in $PATH: unknown

> docker exec -it rtorrent-peioe sh
> OCI runtime exec failed: exec failed: unable to start container process: exec: "sh": executable file not found in $PATH: 

Is there anything I can do about this ?

**Comment by Elegant996** [comment]
Create a container with those packages installed. `rtorrent` is working just fine though. I had to do this for my own image.

**Comment by kannibalox** [comment]
Here's the Dockerfile I use to build it on Ubuntu, if it helps:
```Dockerfile
ARG UBUNTU_VERSION=22.04

FROM ubuntu:${UBUNTU_VERSION} as build

WORKDIR /root/rtorrent

# Install build dependencies
RUN apt update -yqq && apt install -yqq \
    build-essential \
    wget \
    curl \
    bash \
    clang \
    python3 \
    python3-pip

RUN wget -q https://github.com/bazelbuild/bazelisk/releases/latest/download/bazelisk-linux-amd64 -O /usr/local/bin/bazel && chmod +x /usr/local/bin/bazel

# Checkout rTorrent sources from current directory
COPY . ./

# # Checkout rTorrent sources from Github repository
# RUN git clone https://github.com/jesec/rtorrent .

SHELL ["/bin/bash", "-c"]

# Set architecture for packages
RUN if [[ `uname -m` == "aarch64" ]]; \
    then sed -i 's/architecture = \"all\"/architecture = \"arm64\"/' BUILD.bazel; \
    elif [[ `uname -m` == "x86_64" ]]; \
    then sed -i 's/architecture = \"all\"/architecture = \"amd64\"/' BUILD.bazel; \
    fi

# Build rTorrent packages
RUN CC=clang bazel build rtorrent-deb --verbose_failures

# Copy outputs
RUN mkdir dist
RUN cp -L bazel-bin/rtorrent dist/
RUN cp -L bazel-bin/rtorrent-deb.deb dist/

# Now get the clean image
FROM ubuntu:${UBUNTU_VERSION} as rtorrent

WORKDIR /root

# Install rTorrent and dependencies to new system root
COPY --from=build /root/rtorrent/dist/rtorrent-deb.deb .

RUN apt install -yqq ./rtorrent-deb.deb

RUN mkdir /home/download
RUN chown 1001:1001 /home/download

WORKDIR /home/download
# Run as 1001:1001 user
ENV HOME=/home/download
USER 1001:1001

# rTorrent
ENTRYPOINT ["rtorrent"]
```

**Comment by peioe** [comment]
Thanks guys, I'll have a look. I guess this isn't an issue, it's just how this image is made so I am closing this.
